workflows:
  react_native_workflow:
    name: "React Native Build"
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      node: 20.x
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Run tests
        script: npm test
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace ios/english_test.xcworkspace \
            -scheme YourApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CI_WORKSPACE/build/ios/english_test.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $CI_WORKSPACE/build/ios/english_test.xcarchive \
            -exportPath $CI_WORKSPACE/build/ios/ipa \
            -exportOptionsPlist ios/exportOptions.plist
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - build/ios/ipa
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "dotienphong1993@gmail.com"
